CREATE TYPE "product_status" AS ENUM (
  'DRAFT',
  'ACTIVE',
  'INACTIVE',
  'DISCONTINUED'
);

CREATE TYPE "order_status" AS ENUM (
  'PENDING',
  'PAID',
  'SHIPPED',
  'CANCELLED'
);

CREATE TABLE "country" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "merchant" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "country" int,
  "created_at" timestamp
);

CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "serial" varchar,
  "name" varchar(200),
  "merchant" int,
  "price" float,
  "status" product_status,
  "stock" int,
  "created_at" timestamp
);

CREATE TABLE "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" order_status,
  "user_id" int,
  "total" float,
  "created_at" timestamp
);

CREATE TABLE "order_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int
);

ALTER TABLE "merchant" ADD FOREIGN KEY ("country") REFERENCES "country" ("id");

ALTER TABLE "product" ADD FOREIGN KEY ("merchant") REFERENCES "merchant" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");
