CREATE TABLE "users" ("user_id" serial PRIMARY KEY, "username" VARCHAR);

CREATE TABLE "users2" ("user_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "username" VARCHAR);

CREATE TABLE "users3" ("user_id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, "username" VARCHAR);

CREATE TABLE "users4" (
	"user_id" integer GENERATED ALWAYS AS IDENTITY (
		START
		WITH
			100 INCREMENT by 2
	),
	"username" VARCHAR
);

CREATE TABLE "usersDual" (id1 int, id2 int, PRIMARY KEY (id1, id2));


CREATE EXTENSION if NOT EXISTS "uuid-ossp";

SELECT
	gen_random_uuid (),
	uuid_generate_v1 ();

CREATE TABLE "users5" ("user_id" UUID DEFAULT uuid_generate_v4 () PRIMARY KEY, "username" VARCHAR);

CREATE SEQUENCE user_sequence;
DROP SEQUENCE user_sequence;

SELECT
	nextval('user_sequence');

SELECT
	currval('user_sequence'),
	nextval('user_sequence'),
	currval('user_sequence');

SELECT * FROM information_schema.sequences;